# Generated by Django 3.1 on 2020-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, default='', help_text='Leave blank if none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
