# Generated by Django 3.1 on 2020-08-11 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200812_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ended_work',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(models.DateField(null=True)), django.core.validators.MinValueValidator(models.DateField(null=True, validators=[django.core.validators.MinValueValidator(models.DateField(null=True))]))]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='started_work',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(models.DateField(null=True))]),
        ),
    ]
